version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: echo "Hello, world\!"
      - run: echo "SECRET, $SECRET"
      - run: echo "PUBLIC, $PUBLIC"
      - run: echo "A, $A"
